### ISSUE TITLE
Test 4th order discretization

### ISSUE THREAD

**Issue by SCiarella** [DEEPDIP-project/NeuralNS-SciML-Tutorials#1]
The fourth order discretization is not included yet in the test suite. This is toggled by doing `setup(...; order4 = true)`. It would be nice to include some tests for this.

Note (just to keep in mind): The code is currently built with sparse matrices,
which works really well on CPU and Nvidia GPU.

- Boundary contributions are stored in separate vectors
- The code is nice after the matrices are assembled, but it is very hard to
  understand the matrix assembly code
- Assembling these operators requires a lot of memory, especially in 3D
- Other GPUs (e.g. Apple Metal) do not support sparse arrays

I am currently testing an alternative formulation with kernels.
While this is not ready yet, the accompanying documentation is available at
<https://agdestein.github.io/IncompressibleNavierStokes.jl/previews/PR43/>

**Comment by SCiarella** [comment]
The 4th order discretization produces the same results as the RK4 from SciML, so I think that this issue can be marked as completed

**Comment by luisaforozco** [comment]
Great, so I am closing this issue.
